### ISSUE TITLE
Testing `read` function

### ISSUE THREAD

**Issue by amansourian** [abra-eyetracking/abra-eyetracking#13]
We need to further test the reliability of `read` along with code some code formatting.

**Comment by andylikescodes** [comment]
Agree. I am also going to find the testing data for the user defined mode.

BTW, I think posting TODOs and project planning should be under the Projects tab. Maybe Arman you can take a look at that tab and see if we can utilize it for project management. I used it once before for one of the projects I worked on.

**Comment by andylikescodes** [comment]
> Agree. I am also going to find the testing data for the user defined mode.
> 
> BTW, I think posting TODOs and project planning should be under the Projects tab. Maybe Arman you can take a look at that tab and see if we can utilize it for project management. I used it once before for one of the projects I worked on.

Oh I just realized that we are already using this feature under the Abra repo. Never mind. Good job on this.

**Comment by andylikescodes** [comment]
@amansourian Can you be a little bit more specific about what we should do to test this function? Like break down into bullet points so that we can take on it step by step.

**Comment by andylikescodes** [comment]
@AkimaCon Read function needed to be fully tested (please focus on this this week). #29 fix a big issue that it seems to skip trials. One throughout way of testing this is to create a more throughout testing script: e.g. use a for loop to iterate each trial markers and make sure that the data successfully extracted from the file.
